import SidebarLayout from "@/components/sidebar-layout";
import { Metadata } from "next";

export default SidebarLayout;

export const metadata: Metadata = {
  title: "Feeds",
  // description: "Generated by create next app",
};